name: graphql_infra_tool
description: A comprehensive Flutter package providing a robust wrapper around GraphQL operations with built-in error handling, authentication, caching, and logging capabilities.
version: 1.0.1
homepage: https://pub.dev/packages/graphql_infra_tool
repository: https://github.com/benhaxe/graphql_infra_tool
issue_tracker: https://github.com/benhaxe/graphql_infra_tool/issues
documentation: https://pub.dev/packages/graphql_infra_tool

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  graphql_flutter: ^5.2.0
  gql_link: ^1.0.0+1
  gql: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter  # This is what you need
  lints: ^5.0.0
